### ISSUE TITLE
Pagination to load required page directly

### ISSUE THREAD

**Issue by prashanthmadduri** [ldapjs/node-ldapjs#519] opened 2019-08-09 14:16 UTC
Hi Team, 

The library supports pagination and it even has functionality to handle back pressure. However, it seems the library does not have the support to offset.  Is there anyway to load particular page directly instead reading all the results page by page to read particular page. 

Thanks in advance.

**Comment by jsumners** [comment] 2019-08-25 14:44
I do not believe specifying an offset is supported in the LDAP protocol:

https://automatthew.wordpress.com/2007/09/25/paging-in-openldap-or-what-no-limit-or-offset-2/

https://tools.ietf.org/html/rfc2696:
> The client MUST consider the cookie to be an opaque structure and
   make no assumptions about its internal organization or value. When
   the client wants to retrieve more entries for the result set, it MUST
   send to the server a searchRequest with all values identical to the
   initial request with the exception of the messageID, the cookie, and
   optionally a modified pageSize. The cookie MUST be the octet string
   on the last searchResultDone response returned by the server.
   Returning cookies from previous searchResultDone responses besides
   the last one is undefined, as the server implementation may restrict
   cookies from being reused.

**Comment by jsumners** [comment] 2019-08-25 14:45
Closing as this is not feasible at the protocol level.

**Closed by jsumners** 2019-08-25 14:45 UTC

**Comment by jsumners** [comment] 2019-09-08 11:35
Possible resolution in #553

**Comment by jsumners** [comment] 2023-03-10 13:51
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
