### ISSUE TITLE
Filter with umlauts does not work

### ISSUE THREAD

**Issue by simon-lorenz** [ldapjs/node-ldapjs#925] opened 2023-08-03 09:10 UTC
When searching a value that contains umlauts, the filter string is encoded in a way our AD does not seem to understand. It does not return any search results. When searching values without umlauts everything works fine.

Minimal reproduction:

```javascript
import ldapjs from 'ldapjs'

const { EqualityFilter } = ldapjs

console.log(
	new EqualityFilter({
		attribute: `member`,
		value: 'CN=abcö'
	}).toString()
) // -> "(member=CN=abc\c3\b6)"
```

I didn't have this problem with ldapjs v2. Any idea how to fix this?

EDIT: I found [escapeFilterValue](https://github.com/ldapjs/filter/blob/7876f8d451e018eb7b5e07ca1304d8932922cc54/lib/utils/escape-filter-value.js#L5-L17) und [RFC4515](https://datatracker.ietf.org/doc/html/rfc4515), so this seems to work as expected. I'm still not sure if our active directory is to blame, I'm part of a larger corporation and I haven't heard of similar problems in other apps.

**Comment by jsumners** [comment] 2023-08-03 11:25
Duplicate of https://github.com/ldapjs/node-ldapjs/issues/860.

**Closed by jsumners** 2023-08-03 11:25 UTC
