### ISSUE TITLE
Importance of calling unbind

### ISSUE THREAD

**Issue by ORESoftware** [ldapjs/node-ldapjs#365] opened 2016-03-25 00:53 UTC
I have this code:

``` js
                adminClient = ldap.createClient(clientOptions);

                adminClient.bind(ldapConfig.ldapBindAccountDN, ldapConfig.ldapBindAccountPassword, function (err) {
                    if (err) {
                        cb(err);
                    }
                    else {
                        var searchQuery = '(sAMAccountName=' + username + ')';

                        performUserSearch(adminClient, searchQuery, 1, function (err, users) {

                            //adminClient.unbind(function ($err) { //async
                            //
                            //    if ($err) {
                            //        console.error('UNBIND ADMIN CLIENT ERROR: ', $err);
                            //    }
                            //
                            //    if (err) {
                            //        log.error(err);
                            //        cb(err);
                            //    }
                                 if (!users) {
                                    log.debug('Error: no users found at all.');
                                    cb({status: 403, error: new Error('Bad username.')});

// ..... truncated ....
```

As you can see I have commented out the unbind portion. Is it imperative to call unbind? I commented it out, and it doesn't cause any immediate problems. I am having trouble finding information on the purpose of bind/unbind. I assume unbind is important, but then why am I getting away without it? I was getting away without it _before_ I moved to pooled connections. Please enlighten me, thanks.

**Comment by ORESoftware** [comment] 2016-03-25 00:55
unfortuantely, the only info in the docs for unbind are:

```
unbind

unbind(callback)

Performs an unbind operation against the LDAP server.

Example:

client.unbind(function(err) {
  assert.ifError(err);
});
```

**Comment by ORESoftware** [comment] 2016-03-25 01:12
furthermore, if LDAP connections are stateful, does that mean having 100 connections in a pool is at all more costly that a pool of 100 stateless connections?

**Comment by Xotl** [comment] 2016-03-29 22:03
Hi @ORESoftware, i have been using this module too and yes, there's not enough documentation about the `unbinding` method. 

I use that method to close the connection, and it seems to do that because when i run my node app it keeps waiting until i call the unbind method.

**Off topic:** Also i would suggest to you instead of using `if / else` for your error handling do something like this:

```
function (err, someArgs) {
  if (err) {
    // the return will prevent the code
    // outside the if statement to run
    return cb(err);
  }

  // Code if no error here
}
```

**Comment by jsumners** [comment] 2019-08-25 01:26
Closing as the documentation is clarified in #393. Please open a new issue if you have further questions.

**Closed by jsumners** 2019-08-25 01:26 UTC

**Comment by jsumners** [comment] 2023-03-10 13:54
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
