### ISSUE TITLE
Error: spawn useradd ENOENT

### ISSUE THREAD

**Issue by zhaoyiming0803** [ldapjs/node-ldapjs#778] opened 2022-01-04 07:28 UTC
Reference `http://ldapjs.org/guide.html` to add user, but command report error:

``` shell
/etc/passwd LDAP server up at: ldap://0.0.0.0:1389
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn useradd ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn useradd',
  path: 'useradd',
  spawnargs: [ '-m', '-c', 'Created via ldapadd', '-s', '/bin/bash', 'ldapjs' ]
}
```

node version: v16.13.1

npm version: 8.1.2

**Comment by jsumners** [comment] 2022-01-04 12:49
Please provide a minimal reproduction.

**Comment by jsumners** [comment] 2022-03-27 13:01
I'm sorry. It isn't clear what I should be doing with that example. It starts a server and nothing else. But it looks like you are using `child_process` to spawn an external command, and _that_ is what is generating the error. The error you posted originally is stating that the `useradd` binary does not exist. Your `spawn` call should include an environment where the `useradd` binary is in the `PATH`.

**Comment by jsumners** [comment] 2023-02-22 19:22
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.

**Closed by jsumners** 2023-02-22 19:22 UTC
