### ISSUE TITLE
In Memory Example does not work

### ISSUE THREAD

**Issue by laneholcombeatvcp** [ldapjs/node-ldapjs#581] opened 2019-11-23 22:23 UTC
I'm following the instructions here: http://ldapjs.org/examples.html and have started the server (using the unmodified code on the page).

Next I create user.ldif which looks like:
```
dn: cn=ldapjs, o=joyent
objectClass: unixUser
cn: ldapjs
shell: /bin/bash
description: Created via ldapadd
```
I add using ldapadd:
```
ldapadd -H ldap://localhost:1389 -x -D cn=root -w secret -f ./user.ldif 
```
which replies with:
adding new entry "cn=ldapjs, o=joyent"

Then I try to find the entry with ldapsearch:
```
ldapsearch -H ldap://localhost:1389 -LLL -x -D cn=root -w secret -b "o=joyent" cn=ldapjs
```
No such object (32)
Matched DN: o=joyent
Additional information: o=joyent

Where'd I go wrong?

**Comment by jsumners** [comment] 2019-12-15 13:19
I would recommend using the debugger to step through the add and search functions of that example to determine the root cause of the issue. If you determine the issue to be in the example code, we would welcome a PR to fix it.

**Comment by jsumners** [comment] 2023-02-22 19:23
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.

**Closed by jsumners** 2023-02-22 19:23 UTC
