### ISSUE TITLE
SASL bind support

### ISSUE THREAD

**Issue by esamattis** [ldapjs/node-ldapjs#85] opened 2012-07-19 08:55 UTC
There seem to be some TODOs in the code about this. Just creating a ticket to track its progress if you don't mind.

**Comment by FROGGS** [comment] 2022-12-26 16:27
Isnt this issue a duplicate of #29 ?

**Comment by jsumners** [comment] 2022-12-26 17:37
> Isnt this issue a duplicate of #29 ?

I don't know. I have not investigated the two terms enough to say that they are the same.

**Comment by jsumners** [comment] 2023-02-22 19:25
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.

**Closed by jsumners** 2023-02-22 19:25 UTC
Labels: enhancement, has-pr, help-wanted
