### ISSUE TITLE
Update dtrace-provider-bindings dependency

### ISSUE THREAD

**Issue by megakoresh** [ldapjs/node-ldapjs#487] opened 2018-07-18 11:25 UTC
DTrace provider bindings fail to build on mac High Sierra. This is fixed in version `0.8.7`. Can you update the dependency to the next version, so I dont have to always override and use the globally installed version?

**Comment by jsumners** [comment] 2019-08-26 13:40
Resolved by #466.

**Closed by jsumners** 2019-08-26 13:40 UTC

**Comment by jsumners** [comment] 2023-03-10 13:51
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
