### ISSUE TITLE
SearchPager should use CorkedEmitter too

### ISSUE THREAD

**Issue by seewer** [ldapjs/node-ldapjs#722] opened 2021-05-05 20:08 UTC
CorkedEmitter introduced in #610 solves a lot of issues. Sadly when using paged search, SearchPager's childEmitter is still a "normal" EventEmitter and not one with a Cork. This results in concurrency issues for paged searches.

**Comment by seewer** [comment] 2021-05-05 20:15
I'm happy to provide a patch/pr of course. Any ideas if this would need a test as well?

**Comment by jsumners** [comment] 2021-05-06 18:40
PRs are most certainly welcome. Any PR should include test coverage for the included code.

**Comment by seewer** [comment] 2021-05-07 12:20
There (#723) you go. Please not that the issue described here only solved our local problem. By adapting the existing delayed client test to paged searches I discovered that "corking" the childEmitter was the wrong approach. The test covers more cases, so the submitted PR is the better approach.

**Comment by UziTech** [comment] 2021-11-25 06:02
Fixed in v2.3.0 by #723

**Closed by UziTech** 2021-11-25 06:02 UTC

**Comment by jsumners** [comment] 2023-03-10 13:47
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
