### ISSUE TITLE
create a new group

### ISSUE THREAD

**Issue by dlcrista** [ldapjs/node-ldapjs#599] opened 2020-02-25 01:16 UTC
Is it possible to create a group under a base dn with ldapjs? If so, how can this be done? Would I use client.add or client.modify?

Can someone please provide some documentation, as the current documentation is lacking

**Comment by jsumners** [comment] 2020-02-25 02:34
I think the docs are pretty clear in this case -- https://github.com/ldapjs/node-ldapjs/blob/a67303e7a489ab6b487bd0c0dedf67fdcecf7adb/docs/client.md#add

A "group" is just a regular ldap entry with specific attributes.

**Comment by dlcrista** [comment] 2020-02-25 02:49
Thank you for responding!

So the following should work? I want to add a group under a base dn where I have permission to create groups

var entry = {
  cn: 'my_new_group',
  objectclass: 'groupOfNames',
  member: 'cn=somebody,dc=myorg,dc=com'
  description: "testing 123"
};
client.add('my_new_group' + "my_base_dn", entry, function(err) {
  assert.ifError(err);
});

**Comment by jsumners** [comment] 2020-02-25 12:38
Yes? I don't know your schema. Do you get an error? If so, can you reproduce it against in our integration tests on the `next` branch?

**Comment by dlcrista** [comment] 2020-02-25 18:01
Is it possible to use an ldif file to add the group?

**Comment by jsumners** [comment] 2020-02-25 18:12
No. The client library does not parse ldif. You should use standard ldap administration tools if you want to use ldif.

I am closing this thread as it has gone off-topic.

**Closed by jsumners** 2020-02-25 18:12 UTC
Labels: question

**Comment by jsumners** [comment] 2023-03-10 13:49
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
