### ISSUE TITLE
Invalid regular expression in isValidAttributeString

### ISSUE THREAD

**Issue by hasselsjo** [ldapjs/node-ldapjs#863] opened 2023-03-27 13:32 UTC
The method isValidAttributeString in search-request.js returns false when called with a valid one letter attribute such as 'o'.

**Comment by jsumners** [comment] 2023-03-27 13:42
Duplicate of https://github.com/ldapjs/messages/issues/2

**Closed by jsumners** 2023-03-27 13:42 UTC
