### ISSUE TITLE
Feature Request: Paged Query

### ISSUE THREAD

**Issue by Artum** [ldapjs/node-ldapjs#490] opened 2018-08-28 06:37 UTC
It will be nice to have such control for huge dataset queries.

The control standard:
[RFC2696: LDAP Control Extension for Simple Paged Results Manipulation](http://www.ietf.org/rfc/rfc2696)

Some more information on usage:
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/how-ldap-server-cookies-are-handled

**Comment by Artum** [comment] 2018-08-28 12:25
I've just noticed that it might be already implemented!
I'm leaving this ticket open for adding proper documentation since the documentation is poorly explaining how to use the `PagedResultControl`.

**Comment by jsumners** [comment] 2019-08-26 13:51
Closing because I think this has been sufficiently addressed. @Artum if you feel otherwise, feel free to open a PR that updates https://github.com/ldapjs/node-ldapjs/blob/ad451edc18d7768c3ddee1a1dd472d2bbafdae5e/docs/client.md#paging

**Closed by jsumners** 2019-08-26 13:51 UTC
Labels: question

**Comment by jsumners** [comment] 2023-03-10 13:51
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
