### ISSUE TITLE
Search not working in AWS Lambda

### ISSUE THREAD

**Issue by saachinsiva** [ldapjs/node-ldapjs#729] opened 2021-05-20 20:02 UTC
Hello

I am building a small service where we need to get the user details from LDAP. I was able to search the users successfully when I run the code in my desktop however once the code is deployed in AWS lambda, search is not working, from the logs I can see that the ldap connection is good and there are no errors. its just that search is not returning the user info. Please advise.

```
import { Client, SearchOptions, createClient } from 'ldapjs';

import { Injectable } from '@nestjs/common';
import { Config} from '@shared/config/app.config';
import { LogService} from '@shared/services/log/log.service';
import { SecretManagerService} from '@shared/services/secret/secret_manager.service';

@Injectable()
export class DSLdap {
	private client: Client = null;

	constructor(private readonly logService: LogService, private readonly config: Config, private readonly secretService: SecretManagerService) {}

	async config(): Promise<void> {
		let username: string;
		let password: string;

		const secretString: string = await this.secretService.getSecretValue(this.dsConfig.ldap.secretKeyName);
		if (secretString) {
			this.logService.info('LDAP secret retrieved successfully.');
			({ username, password } = JSON.parse(secretString));
		}
		this.logService.info('Connecting to LDAP server...');
		this.client = createClient({
			url: this.config.ldap.url,
			bindCredentials: '',
			tlsOptions: {
				rejectUnauthorized: false
			},
			log: this.logService
		});
		this.logService.info('Connected to LDAP server...');

		await new Promise((resolve, reject) => {
			this.logService.info('Binding to LDAP server...');
			this.client.bind(username, password, (err) => {
				if (err) {
					reject(err);
				}
				this.logService.info('Bound to LDAP server...');
				return resolve(true);
			});

			this.client.on('error', (error) => {
				this.logService.error(error);
				return reject(error);
			});
		});
	}

	async searchByEmail(emailAddress: string): Promise<any> {
		const opts: SearchOptions = {
			filter: `(userPrincipalName=${emailAddress})`,
			scope: 'sub'
		};
		const entries: any = [];
		const referrals: any = [];
		return new Promise((resolve, reject) => {
			this.client.on('error', (error) => {
				this.logService.error(error);
				return reject(error);
			});

			this.client.search(this.config.ldap.baseDn, opts, (err, resp) => {
				if (err) {
					reject(err);
				}
				resp.on('searchEntry', (entry) => {
					this.logService.info('Entry ' + entry);
					entries.push(entry.object);
				});
				resp.on('searchReference', (referral) => {
					this.logService.info('Referral ' + referral);
					referrals.push(referral.uris);
				});

				resp.on('error', (error) => {
					this.logService.error(error);
					return reject(error);
				});

				resp.on('end', (result) => {
					this.logService.info('Result ' + result);
					return resolve({
						entries: entries,
						referrals: referrals
					});
				});
			});
		});
	}
}

```

**Comment by jsumners** [comment] 2021-05-20 20:08
Please provide a minimal reproduction in JavaScript.

**Comment by saachinsiva** [comment] 2021-05-20 20:24
Thanks for getting back to me. We are using Typescript for our server side and the code given above is the one we use.

**Comment by saachinsiva** [comment] 2021-05-20 20:25
> Please provide a minimal reproduction in JavaScript.



<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6NzkyMzI3NCIsInQiOjE2MjE1NDIxNzl9--1e02a5fa8f0bb1084955ccd6f3e3ff526579acc84725048fdb658c6f4a99e6d9" data-channel-target="MDU6SXNzdWU4OTczNzYwNDk=" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box;"><div style="box-sizing: border-box;"><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0NTQ1MjUyNQ==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0NTQ1MjUyNQ==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0NTQ1MjUyNQ==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-845452525" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="600fd78f6d1818dd9dcf96a69bfdd6581454507339ad7606270fa34a140a0e7b" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Thanks for getting back to me. We are using Typescript for our server side and the code given above is the one we use.</task-lists></div><form class="js-comment-update" id="issuecomment-845452525-edit-form" action="https://github.com/ldapjs/node-ldapjs/issue_comments/845452525" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div style="box-sizing: border-box;"><div class="js-timeline-marker js-socket-channel js-updatable-content" id="partial-timeline" data-channel="eyJjIjoiaXNzdWU6ODk3Mzc2MDQ5IiwidCI6MTYyMTU0MjI5MH0=--d2d40b104bb93832e700af34cb990920df869f1d0267fc9ec5bfd37e80b8483a" data-url="/_render_node/MDU6SXNzdWU4OTczNzYwNDk=/issues/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-20T20%3A24%3A49Z" data-last-modified="Thu, 20 May 2021 20:24:49 GMT" data-gid="MDU6SXNzdWU4OTczNzYwNDk=" style="box-sizing: border-box;"></div></div></div></div></div><span id="issue-comment-box" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></span><span style="color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="timeline-comment-wrapper timeline-new-comment js-comment-container js-targetable-element  ml-0 pl-0 ml-md-6 pl-md-3" id="issuecomment-new" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 56px; position: relative; margin-top: 16px; margin-bottom: 0px;"><div class=" d-none d-md-block" style="box-sizing: border-box; display: block !important;"><br class="Apple-interchange-newline">

</div></div></div>

**Comment by UziTech** [comment] 2021-05-20 20:35
`this.client` is an event emitter so you should subscribe to `this.client.on('error' () => {...})` to see if there are any errors thrown there.

**Comment by UziTech** [comment] 2021-05-20 20:35
sorry wrong button...

**Comment by saachinsiva** [comment] 2021-05-20 21:10
> sorry wrong button...

@UziTech 

Thank you for your input. I did not realize that client itself is a subscriber. I added the error event and also updated the code above but still I do not see anything in the log. The same code is working fine in my desktop, however my desktop is in the same network/domain as of our ldap server and I am not sure if it has anything to do with it. I can see that the service was able to connect and perform the search however no info is returned. This is the output I got from end event.

Result {"messageID":3,"protocolOp":"LDAPResult","status":0,"matchedDN":"","errorMessage":"","referrals":[],"controls":[]} 

Logs from Lambda startup.

![image](https://user-images.githubusercontent.com/7923274/119048460-3c696700-b98d-11eb-9d9d-a8bd7d1ba982.png)

Endpoint log:

![image](https://user-images.githubusercontent.com/7923274/119048740-a1bd5800-b98d-11eb-951b-b198086838a4.png)

**Comment by jsumners** [comment] 2021-05-20 21:58
> Thanks for getting back to me. We are using Typescript for our server side and the code given above is the one we use.

This project does not provide support for transpiled code. I also am not willing to try and interpret TypeScript. If you are unable or unwilling to provide a minimal reproduction of the error in JavaScript then I cannot help you.

**Comment by UziTech** [comment] 2021-05-20 22:10
It seems like everything is working if `end` is called. The only thing I can think is the server isn't returning any results for the query for some reason. Unfortunately we are not able to help with that.

**Comment by UziTech** [comment] 2021-05-20 22:13
I did notice one but in your code:

```diff
  this.client.search(this.config.ldap.baseDn, opts, (err, resp) => {
    if (err) {
-     reject(err);
+.    return reject(err);
    }
```

**Comment by saachinsiva** [comment] 2021-05-20 22:31
@UziTech  @jsumners 

Thanks again. I will try to convert this code to JavaScript later and can share it with you. I will also check with our LDAP admin if they see anything on their side.

**Comment by DanielSamsonraj** [comment] 2021-06-07 10:59
@saachinsiva 
Were you able to solve this issue?

**Comment by saachinsiva** [comment] 2021-06-07 11:05
@DanielSamsonraj 

Not yet but I believe the LDAP server is throwing certificate error but has been ignored silently by this library. I may need to add the certificate to the truststore to see if it works. I have been working on other high priority item not but will keep you posted if I make any progress.

**Comment by saachinsiva** [comment] 2021-06-15 11:30
@DanielSamsonraj 

I tried adding the certificate to the nodejs env and it works perfectly fine in local but still no luck in lambda. No error nothing...just get empty response.

**Comment by saachinsiva** [comment] 2021-06-15 17:33
Hello Everyone,

I was able to make it work. The problem is with webpack. When we bundle the application, webpack config uses managle and also rename the functions and classes name to smaller character in order to save space which affects the event emitter. In my case the function name SearchEntry is replaced with character 'y' due to mangle and this causes issue when it reaches this line of code " msg.constructor.name" in manageCallback shown below where it expects the constructor name as SearchEntry which will then be changed to searchEntry and send that as an event.  However in my case the constructor name is coming as 'y' and the event is emitted as 'y' which is why it is not getting any results. In order to keep the function name and class name I used below config for my webconfig.

From client.js

```
 function messageCallback (msg) {
    if (timer) { clearTimeout(timer) }

    log.trace({ msg: msg ? msg.json : null }, 'response received')

    if (expect === 'abandon') { return sendResult('end', null) }

    if (msg instanceof SearchEntry || msg instanceof SearchReference) {
      let event = msg.constructor.name
      event = event[0].toLowerCase() + event.slice(1)
      return sendResult(event, msg)
    } else {
      tracker.remove(message.messageID)
      // Potentially mark client as idle
      self._updateIdle()

      if (msg instanceof LDAPResult) {
        if (expect.indexOf(msg.status) === -1) {
          return sendResult('error', errors.getError(msg))
        }
        return sendResult('end', msg)
      } else if (msg instanceof Error) {
        return sendResult('error', msg)
      } else {
        return sendResult('error', new errors.ProtocolError(msg.type))
      }
    }
  }
```


Webpack fonfig:

minimizer: [
	new TerserPlugin({
		terserOptions: {
			mangle: true,
			**keep_classnames: true,
			keep_fnames: true,**
			sourceMap: true
		},
		parallel: true
	})
]

**Comment by jsumners** [comment] 2021-06-15 17:57
Closing this as it sounds like you have found your issue and solution.

Reminder: we do not support transpiled versions of the library.

**Closed by jsumners** 2021-06-15 17:57 UTC

**Comment by jsumners** [comment] 2023-03-10 13:47
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
