### ISSUE TITLE
webpack minimized can not works

### ISSUE THREAD

**Issue by heifade** [ldapjs/node-ldapjs#739] opened 2021-06-25 02:19 UTC
When I run it local it works very well. But when I minimized it with webpack, it can not works. Because event: 'searchEntry' not been called, but event: 'end' called

code

export async function loginCheck(pars: { userAd: string; password: string; adDC: string; adServer: string }): Promise<boolean> {
  const { userAd, password, adDC, adServer } = pars;
  const client = createClient({
    url: `ldap://${adServer}`,
  });
  const [dc, userName] = userAd.split("\\");
  const opts: SearchOptions = {
    filter: `(sAMAccountName=${userName})`,
    scope: "sub",
    timeLimit: 500,
  };
  console.log(0, userAd, password, adDC, adServer);
  return new Promise((resolve, reject) => {
    console.log(1);
    client.bind(userAd, password, (err1, res1) => {
      console.log(2);
      if (err1) {
        reject(err1);
        client.unbind();
        client.destroy();
        return;
      }
      console.log(3);
      client.search(`DC=${dc},DC=${adDC},DC=com`, opts, (err2, res2) => {
        console.log(4);
        if (err2) {
          reject(err2);
          client.unbind();
          client.destroy();
          return;
        }
        res2.on("searchEntry", (entry) => {
          console.log('loadin success');
          resolve(true);
          client.unbind();
          client.destroy();
        });
        res2.on("error", (err3) => {
          console.log(5);
          if (err3) {
            reject(err3);
            client.unbind();
            client.destroy();
            return;
          }
        });
        res2.on("end", (r) => {
          console.log(8, r.errorMessage, r.json, r.toString());
        });
      });
    });
  });
}

**Comment by UziTech** [comment] 2021-06-25 04:13
duplicate of https://github.com/ldapjs/node-ldapjs/issues/729#issuecomment-861696066

**Closed by UziTech** 2021-06-25 04:13 UTC

**Comment by jsumners** [comment] 2023-03-10 13:46
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
