### ISSUE TITLE
"No Such Object" when using Client Modify

### ISSUE THREAD

**Issue by audn** [ldapjs/node-ldapjs#923] opened 2023-08-02 12:24 UTC
I'm getting "No Such Object" error when I try to modify a group, even though the DN provided is correct.

I added `Bunyan` to inspect logs, and I could see from the response that `object` was empty.
```tsx
const client = ldap.createClient({
   url: 'LDAPS:/xxx',
   tlsOptions: {
      rejectUnauthorized: true,
      cert: fs.readFileSync('xx.pem'),
      ca: fs.readFileSync('xxx.pem'),
   },
   reconnect: false,
   log: new Bunyan({
      name: 'ldapjs',
      component: 'client',
      stream: process.stderr,
      level: 'trace',
   }),
});
```
Response:
```json
{
   "name": "ldapjs",
   "component": "client",
   "hostname": "x",
   "pid": 33960,
   "clazz": "Client",
   "ldap_id": "x",
   "level": 10,
   "msg": "sending request {\"messageId\":3,\"protocolOp\":102,\"type\":\"ModifyRequest\",\"object\":{},\"changes\":[{\"operation\":\"add\",\"modification\":{\"type\":\"member\",\"values\":[\"CN=xx\"]}}],\"controls\":[]}",
   "time": "2023-08-02T11:58:39.461Z",
   "v": 0
}
```
Function for modifying:
```tsx
client.modify('cn=foo,dc=example,dc=com', change, (err) => {
   if (err) {
      console.log(err);
      reject(new Error(err.message));
   } else {
      console.log('la til i gruppe %j', null);
      resolve(null);
   }
});
```

I solved it by manually editing the ensureDN function in the `\node_modules\ldapjs\lib\client\client.js` file from:
```tsx
function ensureDN(input) {
  if (DN.isDn(input)) {
    return DN
  } else if (typeof (input) === 'string') {
    return DN.fromString(input)
  } else {
    throw new Error('invalid DN')
  }
}
```

To:
```tsx
function ensureDN(input) {
  if (DN.isDn(input)) {
    return DN
  } else if (typeof (input) === 'string') {
    return input // instead of DN.fromString()
  } else {
    throw new Error('invalid DN')
  }
}
```

Is this a known issue, or am I missing something?

**Comment by jsumners** [comment] 2023-08-02 12:26
> Is this a known issue, or am I missing something?

https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.4

**Comment by audn** [comment] 2023-08-02 12:28
Sorry I forgot to mention. I am on 3.0.4

**Comment by audn** [comment] 2023-08-02 12:50
The only way I've been able to fix this is by returning `input` instead of `DN.fromString(input)`. 

The `DN.isDn()` function seems to return false, even for the example DN used in the docs: `cn=foo,dc=example,dc=com`

**Comment by jsumners** [comment] 2023-08-03 14:23
I have created an integration test based upon this issue https://github.com/ldapjs/node-ldapjs/pull/926

I am not seeing the issue described.

**Comment by jsumners** [comment] 2023-08-04 16:37
Closing as cannot reproduce. If you are able to provide a reproduction, or show how the integration test I added is insufficient, please reopen with that information.

**Closed by jsumners** 2023-08-04 16:37 UTC

**Comment by audn** [comment] 2023-08-07 07:12
https://github.com/audn/ldapjs-reproduction
Let me know if it works on your end @jsumners

**Comment by jsumners** [comment] 2023-08-07 11:15
Have you reviewed the integration test I added? Can you point out how it does not cover the issue?

Regarding your repo:

1. https://github.com/audn/ldapjs-reproduction/blob/06453eb1342cf8fd371c3a3a700e648fd4ae29b5/package.json#L6 is not v3.0.4. The v3.0.4 release directly addresses the code block you are asserting is the issue.
2. It is not a minimal reproduction. Please review https://stackoverflow.com/help/minimal-reproducible-example. Note: the integration test I provided is a good example of what a minimal reproduction looks like for this project.

**Comment by audn** [comment] 2023-08-08 10:17
I tried moving the user, and that fixed it. Do you have any limitations as of how deep we can drill?

Doesn't work: `CN=user1,OU=Portal,OU=Users,OU=Tier,OU=Norge,DC=example,DC=com`
Works: `CN=user1,DC=example,DC=com`

**Comment by jsumners** [comment] 2023-08-08 11:59
You have removed your code, so I cannot see what you are doing. I'm going to guess that you are searching for the entry to modify, setting a base DN at `dc=example,dc=com`, and **not** specifying `scope=subtree`.

This library does not impose any limits on DNs that are not present in the RFCs.

**Comment by audn** [comment] 2023-08-09 04:29
Can you add `scope` on `modify`?

https://github.com/audn/ldapjs-reproduction

**Comment by audn** [comment] 2023-08-10 11:21
It seems like it's returning "No Such Object" when using "ø" in the DN @jsumners

**Comment by jsumners** [comment] 2023-08-10 11:22
Please see https://github.com/ldapjs/node-ldapjs/issues/860.
