### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by RaymondLC92** [ldapjs/node-ldapjs#461] opened 2017-12-01 21:38 UTC
I've noticed that the last commit was some time ago. and that there are quite a number of open issues with no reply.

**Comment by Caballerog** [comment] 2017-12-29 09:30
That's a important question...

**Comment by joshuacox** [comment] 2018-01-12 12:29
This is a very important question.  Issues remain unanswered, Pull Requests are unmerged, and there is no activity in the commits.@joyent should be ashamed of their treatment of this project.  @mcavage doesn't seem to get notifications anymore either.

**Comment by RaymondLC92** [comment] 2018-01-12 16:04
Indeed it seems to be dead in the water.

Unfortunate as it would've been really nice not to have to roll our own solution.

**Comment by Caballerog** [comment] 2018-02-05 21:11
@joyent would you find another maintainer ?

**Comment by zelein** [comment] 2018-02-14 17:50
We've been maintaining an internal fork up to this point. This project hasn't seen any activity in some time.

**Comment by jsumners** [comment] 2019-08-26 12:21
Duplicate of #488 (well, 488 is the dupe, but it has more discussion).

**Closed by jsumners** 2019-08-26 12:21 UTC

**Comment by jsumners** [comment] 2023-03-10 13:52
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
