### ISSUE TITLE
LDAP query returns nothing and does not raise any error

### ISSUE THREAD

**Issue by suityou01** [ldapjs/node-ldapjs#626] opened 2020-06-12 14:22 UTC
Please find below a full code example of the problem.

Note, no errors are returned, and none of the emitter events fire. The query works from the same machine on the command line using open-ldap and the same parameters.

```js
import ldap from 'ldapjs';
import assert from 'assert';

let client = ldap.createClient({
    url: 'ldap://192.168.1.102'
});

client.bind('administrator@corp.example.com', 'ThisIsMyAdminPassword!', function(err) {
    assert.ifError(err);
});

var opts = {
    filter: '(objectclass=user)',
    scope: 'sub',
    attributes: ['dn', 'sn', 'cn']
  };

client.search('dc=corp,dc=example,dc=com', opts, function(err, res) {
    res.on('searchEntry', function(entry) {
        console.log('entry: ' + JSON.stringify(entry.object) + '\n');
    });
    res.on('searchReference', function(referral) {
        console.log('referral: ' + referral.uris.join() + '\n');
    });
    res.on('error', function(err) {
        console.error('error: ' + err.message + '\n');
    });
    res.on('end', function(result) {
        console.log('status: ' + result.status + '\n');
    });

});
```

And the command line equivalent

```
ldapsearch -b "DC=corp,DC=example,DC=com" -H ldap://192.168.1.102 -D "administrator@corp.example.com" -w ThisIsMyAdminPassword! -s sub "(objectclass=user)"
```

**Comment by jsumners** [comment] 2020-06-13 11:42
[ldap-example.zip](https://github.com/ldapjs/node-ldapjs/files/4774521/ldap-example.zip)

**Comment by thebpmgroup** [comment] 2020-06-13 11:58
Thank you sir. Yes this works well and I am truly grateful for your time. I would say the code I am trying uses ES6 import syntax. This is the only difference I can spot. But it is a big difference and makes the difference between working and not working. This of course is out of scope for this ticket, but if I do stumble upon a solution I will of course report back.

I'm looking at using @std/esm but that's a horrible hack.

**Comment by jsumners** [comment] 2020-06-13 12:02
We do not support transpiled code.

**Closed** 2020-06-13 12:02 UTC

**Comment by thebpmgroup** [comment] 2020-06-13 12:21
Interesting. Your code has types and interfaces which are not JavaScript constructs, but to my untrained eye looks like Typescript. Is this not transpiled?
Asking for a friend.

**Comment by jsumners** [comment] 2020-06-13 14:19
None of this is TypeScript. Any TS files you may be using come from third parties.

**Comment by thebpmgroup** [comment] 2020-06-13 14:27
Typescript being in a file with a ts extension is merely a convention.

In the index.js file there are declared types and interfaces. This is Typescript. Hence my current confusion.

**Comment by suityou01** [comment] 2020-06-13 14:38
```
export function createClient(options?: ClientOptions): Client;
```

This is typescript

**Comment by jsumners** [comment] 2020-06-13 14:39
Please provide a link. There is only plain JavaScript in this repository.

**Comment by suityou01** [comment] 2020-06-13 14:43
This is the path on my machine

cache/typescript/3.8/node_modules/@types/ldapjs

```
// Type definitions for ldapjs 1.0
// Project: http://ldapjs.org
// Definitions by: Charles Villemure <https://github.com/cvillemure>, Peter Kooijmans <https://github.com/peterkooijmans>, Pablo Moleri <https://github.com/pmoleri>, Michael Scott-Nelson <https://github.com/mscottnelson>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
```

**Comment by suityou01** [comment] 2020-06-13 14:44
As I am not using Typescript, and this is not in your repository I don't understand what is happening.

**Comment by jsumners** [comment] 2020-06-13 17:33
Again, that is from a third party that has nothing to do with this organization. We do not maintain those types. 

Your IDE, editor, or some other aspect of your development environment is downloading that package.

**Comment by thebpmgroup** [comment] 2020-06-13 17:37
That would be npm.

**Comment by jsumners** [comment] 2020-06-13 17:43
No sir. npm only installs what you tell it to. If you look through the `package-lock.json` included in the zip file posted earlier in this thread you will see any reference to the `@types` module.

**Comment by jsumners** [comment] 2023-03-10 13:49
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
