### ISSUE TITLE
Obtaining search entry attribute value by key

### ISSUE THREAD

**Issue by matko031** [ldapjs/node-ldapjs#960] opened 2023-12-17 11:10 UTC
I can't find any information in the documentation about obtaining the attribute value by the attribute name from search result. `searchEntry.pojo` contains a list of attibutes with values, but no direct mapping. Basically I would expect there to be a way of doing something like `searchEntry.sn` to get value(s) of `sn` attribute for given search entry, but I can't figure out a way to do that? Is it a framework limitation or did I miss something in the documentation?

**Comment by jsumners** [comment] 2023-12-17 19:13
Duplicate of https://github.com/ldapjs/node-ldapjs/issues/841.

**Closed by jsumners** 2023-12-17 19:13 UTC
