### ISSUE TITLE
No support for Norwegian Letters 

### ISSUE THREAD

**Issue by audn** [ldapjs/node-ldapjs#933] opened 2023-08-15 07:06 UTC
Specific letters such as "ÆØÅ" isn't working properly.
```js
const baseDN = parseDN('ou=Norge Gjøvik,dc=planetexpress,dc=com');
baseDN.toString(); // outputs 'ou=Norge Gjc3\b8vik,dc=planetexpress,dc=com'
```

![image](https://github.com/ldapjs/node-ldapjs/assets/21041399/e135cb00-6c27-4ac5-b16b-6253cae354c2)

**Comment by jsumners** [comment] 2023-08-16 16:28
This is a duplicate of #860. Please follow that issue.

**Closed by jsumners** 2023-08-16 16:28 UTC
