### ISSUE TITLE
TypeError: Cannot destructure property 'message' of 'tracker.fetch(...)' as it is null

### ISSUE THREAD

**Issue by BryanHunt** [ldapjs/node-ldapjs#890] opened 2023-05-25 13:50 UTC
ldapjs 3.0.2

I'm getting an occasional crash with the following error.  I do have an error handler registered with the client, so I think this is a case that is not covered.

```
/app/node_modules/ldapjs/lib/client/client.js:884
      const { message: trackedMessage, callback } = tracker.fetch(message.messageId)
                       ^
TypeError: Cannot destructure property 'message' of 'tracker.fetch(...)' as it is null.
    at Parser.onMessage (/app/node_modules/ldapjs/lib/client/client.js:884:24)
    at Parser.emit (node:events:513:28)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:135:8)
    at TLSSocket.onData (/app/node_modules/ldapjs/lib/client/client.js:875:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by jsumners** [comment] 2023-05-25 15:37
A minimal reproduction will be needed to provide support on this.

**Comment by BryanHunt** [comment] 2023-05-27 14:00
This problem occurs maybe once a day out of 5 running instances.  Reproduction is going to be impossible.  My recommendation is to add a check for the case described in the error message and emit an error back to the client.  That way, I can handle the error in my code rather than the application crash.

**Comment by BryanHunt** [comment] 2023-05-27 22:43
So you are fine with applications crashing that use your code?

**Comment by jsumners** [comment] 2023-05-27 23:57
I asked for more information. You declined to give it. I cannot diagnose a problem without a reproduction. There should be zero instances that a message is unavailable. So there is most likely some issue in whatever ldap conversation that resulted in the report.

I am quite willing to collaborate on a diagnosis and solution if you are, but we'll need a reproduction.

**Comment by janiago** [comment] 2023-06-08 02:22
I have met the same issue in my production ENV. I can try to catch it as "uncaughtException" on process level, but it's not a long term solution. Hope the issue can be solved, otherwise we have to change our LDAP solution.
Thanks!

**Comment by benzhuo** [comment] 2023-06-08 07:11
In index.js  line 91
function  ** tracker.fetch ** returns **null**  if neither tracked==true   nor abandonedMsg==true 
which will cause line 884 in client.js **crash** 
    _const { message: trackedMessage, callback } = tracker.fetch(message.messageId)_

TypeError: Cannot destructure property 'message' of 'tracker.fetch(...)' as it is null.

-----------------------------------------------------------------------------  
tracker.fetch = function fetchMessage (msgID) {
    const tracked = messages.get(msgID)
    if (tracked) {
      purgeAbandoned(msgID, abandoned)
      return tracked
      return null
    }

    // We sent an abandon request but the server either wasn't able to process
    // it or has not received it yet. Therefore, we received a response for the
    // abandoned message. So we must return the abandoned message's callback
    // to be processed normally.
    const abandonedMsg = abandoned.get(msgID)
    if (abandonedMsg) {
      return { message: abandonedMsg, callback: abandonedMsg.cb }
    }

    return null
  }

**Comment by jsumners** [comment] 2023-06-08 11:34
Thank you for the diagnosis @benzhuo. It at least gives us something to go on.

It looks like the difference is the following:

**v2.x**:
https://github.com/ldapjs/node-ldapjs/blob/92dfc80fd169f889cf2e0de53ff140ef2887c1c7/lib/client/client.js#L878-L889

**v3**:
https://github.com/ldapjs/node-ldapjs/blob/f2890088e49c0c7b7b880998d73d6e4a448d7b4e/lib/client/client.js#L878-L920

The short of it is: we neglected to recognize that `tracker.fetch` can return `null` under some (still unknown) circumstance(s). I really wish we could figure out what those circumstances are, but I think we can introduce some logging here to give us a clue.

**Comment by benzhuo** [comment] 2023-06-30 08:27
Hi Jsumners,
   When will a new version is available? is there a plan?

**Comment by jsumners** [comment] 2023-06-30 11:34
Please recognize that we are not in the same parts of the world and that while you are awake I am asleep. I also need to take time to verify that proposed changes cover the issue correctly, and my current priority is finding gainful employment.

**Comment by benzhuo** [comment] 2023-07-03 00:18
Thanks a lot..

**Comment by benzhuo** [comment] 2023-07-03 08:38
I understand, hope this can be released as soon. good luck, there will be bread.

**Comment by jsumners** [comment] 2023-07-04 12:59
https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.3

**Closed by jsumners** 2023-07-04 12:59 UTC

**Comment by benzhuo** [comment] 2023-07-05 03:48
Thanks, jsumner
