### ISSUE TITLE
AD-Group with more than 1500 members

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ldapjs/node-ldapjs#582] opened 2019-11-29 00:27 UTC
I am using ldapjs to retrieve all members in an AD-group, but after adding member number 1500 in the group ldapjs just returns the name of the group but no members

Using the commandline version of ldapsearch I got the same result, so i searched for a solution here and found that i can add "members;range=1500-*" as an attribute, and will then get the next 1500 members.

but trying the same solution in ldapjs by setting attributes attributes: ['member;range=1500-2000' ] does still not return any of the members

using attributes: ['member;range=0-20' ] for a group with less than 1500 members will not return any members.

It would have been nice if the paging did take care of this, but paging seems to be on a higher level. Any ideas about how to retrieve all members from a large AD-group?

**Comment by jsumners** [comment] 2019-11-29 14:29
The AD specific wrapper on top of this library uses a [`PagedResultsControl`](https://github.com/ldapjs/node-ldapjs/blob/5354e9cda6e97b5344d8bdc09729d5843ee8008d/lib/controls/paged_results_control.js) to retrieve result sets with many results -- https://github.com/jsumners/node-activedirectory/blob/9f0d92be752d782de3b05ae2620a4bb9c3c4118c/lib/components/search.js#L72-L85

**Comment by ThorvaldAagaard** [comment] 2019-11-29 15:19
Yes and that works fine if the paging is due to many responses, but paging for members in a group works in another way

**Comment by jsumners** [comment] 2019-12-02 13:20
My understanding of LDAP is that everything works by searches, and searches are paged using the aforementioned control. It doesn't matter if it is a search for "group names" or "members of a specific group".

**Comment by ThorvaldAagaard** [comment] 2019-12-02 13:52
Well then you might have to change your understanding :-)

But I think it is because I am searching for groups and retrieving members, as far as I know there is no query that returns members for a specific group

But I have found another implementation, that works: https://github.com/zont/ldapjs-client

```
    // Fetching 100 members each time
    var users = [];
    var pageSize = 100;
    var start = 0
    var end = pageSize - 1;
    var fetched = false;
    var domain = "Enter your domain here"    
    while (!fetched) {
        var range = 'member;range=' + start + '-' + end;
        const options = {
            filter: '(cn=' + group + ')',
            scope: 'sub',
            attributes: ['dn', 'sn', 'cn', range]
        };
        console.log("Fetching: " + range);
        const entries = await client.search(domain, options);
        if (!entries[0]) {
            fetched = true;
        } else {
            //console.log(entries[0].cn);
            if (entries[0]['member;range=' + start + '-*']) {
                range = 'member;range=' + start + '-*';
                fetched = true;
            }
            // If only one member returned it will not be an array
            if (Array.isArray(entries[0][range])) {
                console.log("Elements: " + entries[0][range].length);
                var fields;
                entries[0][range].forEach(element => {
                    fields = element.split(',');
                    users.push(fields[0]);
                });
            } else {
                var fields;
                fields = entries[0][range].split(',');
                users.push(fields[0]);
            }
        }
        start += pageSize;
        end += pageSize;
    }
```
So all scrolling is done using attributes with a syntax like member;range=0-99, and if more members requested than exist, then it will be returned with attribute member;range=xx-* telling its the last

Sample output (With range 0-10)

![image](https://user-images.githubusercontent.com/10560652/69964716-28207880-1513-11ea-858b-0a7df03b85bd.png)

**Comment by jsumners** [comment] 2019-12-02 13:56
If there is an issue then PRs are welcome. At the very least a reproducible test case.

**Comment by ThorvaldAagaard** [comment] 2019-12-02 14:02
I think the simple test case is just to add more than 1500 members in a group and the make a search for that group and including members as a wanted attribute.

Up til 1499 members all will work ok, but when you add member no 1500, no members are returned.

I think the reason is that when LDAP sees 1500+ members the attribute name is changed from **member** to **member;range=0-1499** 
And then you will, as in my sample, have to specify the range you want members for.

**Comment by jsumners** [comment] 2019-12-07 15:37
I have added an integration test in #585 to address this issue. The test passes as expected. Please review the test. If you can submit a PR that reproduces the error, that would be great.

**Comment by jsumners** [comment] 2019-12-09 02:40
> I have implemented your test in local code, and is testing against two different groups
> 
> Just before the code
> 
> ```
>         const memberAttr = results[0].attributes.find(a => a.type === 'member')
>         t.ok(memberAttr)
>         t.ok(memberAttr.vals)
>         t.type(memberAttr.vals, Array)
>         t.is(memberAttr.vals.length, 2000)
> ```
> 
> I did add the following
> 
> ```
> results[0].attributes.forEach(attr => {
>                     console.log(attr.type)                    
>                 })
> ```
> 
> And the output from a small group is
> 
> > objectClass
> > cn
> > description
> > member
> > distinguishedName
> > instanceType
> > whenCreated
> > whenChanged
> > uSNCreated
> > uSNChanged
> > name
> > objectGUID
> > objectSid
> > sAMAccountName
> > sAMAccountType
> > groupType
> > objectCategory
> > dSCorePropagationData
> 
> and the output from the large group is
> 
> > objectClass
> > cn
> > description
> > member
> > member;range=0-1499
> > distinguishedName
> > instanceType
> > whenCreated
> > whenChanged
> > uSNCreated
> > uSNChanged
> > name
> > objectGUID
> > objectSid
> > sAMAccountName
> > sAMAccountType
> > groupType
> > objectCategory
> > dSCorePropagationData
> 
> and for the large group the test failed as memberAttr.vals.length was 0
> 
> but using
> 
> ```
> const memberAttr2 = entry.attributes.find(a => a.type === 'member;range=0-1499')
> ```
> 
> did return the first 1500 users in the group

@ThorvaldAagaard please don't mix up issues.

I assume the above quote about "local code" is against an Active Directory server. If that is not the case, please state your setup. But if it is, the case, then this issue is not with the library but your server. See:

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/e27b48db-6f82-44cd-9038-2e54f790cc1f

https://social.technet.microsoft.com/Forums/office/en-US/4de2f4aa-0683-46e4-9229-ee25ac1dda36/increase-the-maximum-number-of-values-for-an-attribute-in-active-directory-2008r2

**Comment by ThorvaldAagaard** [comment] 2019-12-09 12:46
Yes, you are right I am running against an active directory server, I realized that I did not make that a clear statement, (thus the headline was AD-group with 1500+ members)

If this repository is just for setting up your own ldap-server and using the client code to access that server, you are right, that I am messing things up, and I will just keep using https://github.com/zont/ldapjs-client

You could put a mention of that in the readme, as I was expection the package to be used as a client to any LDAP-server

Sry, for that, and you are welcome to close this issue, and anyway using 
```
const memberAttr2 = entry.attributes.find(a => a.type === 'member;range=0-1499')
```
it is possible to use this package to get all members also from AD, but it will need some handling of the ranges

**Comment by jsumners** [comment] 2019-12-09 13:21
> If this repository is just for setting up your own ldap-server and using the client code to access that server

I did not say that. `ldapjs` is a general purpose LDAP library. However, Active Directory is not a standard LDAP server. You either need to write LDAP search queries according to AD's modifications, or you need to configure your AD server to return results as you expect them.

It is very likely the other library is _not_ a general purpose LDAP library. It is quite likely it is developed against an AD server and thus incorporates AD specific quirks into its code.

I _will_ close this issue as I think it has been sufficiently addressed. If you think otherwise, and are able to show as much via a failing test case, then you are welcome to reopen it.

**Closed by jsumners** 2019-12-09 13:21 UTC

**Comment by jsumners** [comment] 2023-03-10 13:49
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
