### ISSUE TITLE
How to gracefully close connection to the server (as a client)?

### ISSUE THREAD

**Issue by regulatre** [ldapjs/node-ldapjs#382] opened 2016-06-15 20:06 UTC
I'm using ldapjs as a client and I would like to gracefully close the connection when I'm done performing my query. I can't find a way to do this. Is it possible? Thanks!

**Comment by nixelsolutions** [comment] 2016-06-19 18:27
I'm in the same case, seems like I'm suffering a connection leak :(

**Comment by geoffginley** [comment] 2016-06-19 18:49
Are you guys are using SSL and getting a "ECONNRESET" which crashes node? If so I was previously having the same issue and did 2 things

1. I wrap the work in a function, I still use client.unbind() but since doing this I have not seen re-occurences.
2. I catch the exception just in case so it doesn't crash node

`process.on('uncaughtException', function (err) {
  if (err.code === "ECONNRESET") {
    console.log(err.stack);
  } else {process.exit;}
})`

I should also add I've had similar issues with TLS outside of ldapjs

**Comment by nixelsolutions** [comment] 2016-06-19 19:28
No, in my case just found it was a problem with passport ldap strategy. Unbind is working OK and actually closing connections in the right way. Passport was leaking connections cause my implementation wasn't unbinding connections.

**Comment by UziTech** [comment] 2016-06-23 18:19
The ldap client has an undocumented method called `destroy` that will close the connection and not allow reconnection

https://github.com/mcavage/node-ldapjs/blob/master/lib/client/client.js#L974

**Comment by gbouthenot** [comment] 2016-11-22 12:35
Thank you !

**Comment by gbouthenot** [comment] 2016-11-22 12:37
Thank you ! Calling ```client.destroy()``` inside the search callback closes the connection.

**Comment by prajnavantha** [comment] 2018-04-10 21:16
Is doing `client.destroy()` a right thing to do?
Won't destroying the connection and again recreating it, affect the performance.
I'm using `client.destroy()` presently but not sure of the right way. Maybe reusing the same connection is ideal...

After i tried the option `reconnect: true` i could find that once the connection is reset its getting connected again.  This may be a right thing to do but need further inputs from all...

**Comment by minotaurrr** [comment] 2018-04-13 00:50
@prajnavantha Are you getting the ECONNRESET error with the `reconnect: true` option?

**Comment by prajnavantha** [comment] 2018-04-13 11:04
No... I'm not getting an ECONNRESET after `reconnect: true`. It seems to be working fine. I'm still observing though.

**Comment by jsumners** [comment] 2019-08-25 01:26
Closing as the documentation is clarified in #393. Please open a new issue if you have further questions.

**Closed by jsumners** 2019-08-25 01:26 UTC

**Comment by jsumners** [comment] 2023-03-10 13:53
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
